### ISSUE TITLE
Too few arguments to Parser

### ISSUE THREAD

**Issue by djKooks** [contentful/rich-text.php#32]
Hello,
I caught an error when calling parser and renderer for RichText
```
2019/03/19 06:21:17 [error] 6#6: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Contentful\RichText\Parser::__construct(), 0 passed in /var/www/html/include/contentful_function.php on line 82 and at least 1 expected in /var/www/html/assets/vendor/contentful/rich-text/src/Parser.php:45
```

My code is:
```php
...
    $parser = new Contentful\RichText\Parser();
    $renderer = new Contentful\RichText\Renderer();
    
    $node = $parser->parse($data);
...
```

What parameter do I have to put on `Parser` constructor?

Thanks.

**Comment by dborsatto** [comment]
This package is designed to be used automatically by the Delivery SDK, and shouldn't really be created manually. If for whatever reason you still want to use this library standalone, you need to provide an instance of [`Contentful\Core\Api\LinkResolverInterface`](https://github.com/contentful/contentful-core.php/blob/master/src/Api/LinkResolverInterface.php), which is responsible for converting a `Contentful\Core\Api\Link` object (a Contentful link) into an actual resource. You can check the Delivery SDK implementation for reference: https://github.com/contentful/contentful.php/blob/master/src/LinkResolver.php

Cheers,

Davide

**Comment by Sebb767** [comment]
Hey @getrealtec ,

@dborsatto no longer maintains this library. The readme should've been updated, since we had previous confusion - I'm sorry, that's on me.

On using this library stand-alone, we don't really support this use-case. That being said, simply implementing the link resolver interface to resolve to your types would be an option (see [here](https://github.com/contentful/rich-text.php/blob/c9a34901080d8b94209453a1321b458a74f9e75c/src/NodeMapper/AssetHyperlink.php#L31-L33) for an example on how it's used). You'd still need to import `Contentful/Core` by dependency, but you wouldn't need to use it in any way.
