### ISSUE TITLE
link resolver.

### ISSUE THREAD

**Issue by unprintedch** [contentful/rich-text.php#66]
Hello

I'm trying the get some nice html from the json i get from the graphql api using php.
But i keep stuck with the "You will also need a link resolver to instanciate the parser."
I have absolutely no idea how to get it.
I there a way to have a full working example from the call to the render?
Is what i'm trying even correct?

**Comment by Sebb767** [comment]
Hi @davouid ,

this library is not usually used on its own, therefore, this is not straight-forward :)
You basically have three options here:

1. Use the link resolver from the Contentful Client, see here: https://github.com/contentful/contentful.php/blob/master/src/Client.php#L154 . It's not accessible by default, but you can copy the steps from the constructor or inherit from it to add a Getter. I can also add a Getter, since we'll be having a release for Contentful very soon.
2. Create your own implementation of the LinkResolver that doesn't actually resolve links. If you don't have embedded entries or assets, this is probably the easiest solution. 
3. Create your own LinkResolver that resolves Links using the GraphQL API


Here's an example for 2:
```
class NullLinkResolver implements \Contentful\Core\Api\LinkResolverInterface {

    public function resolveLink(Link $link, array $parameters = []): \Contentful\Core\Resource\ResourceInterface
    {
        throw new \Exception("Found a link, but this class can not resolve links!");
    }

    public function resolveLinkCollection(array $links, array $parameters = []): array
    {
        throw new \Exception("Found a link, but this class can not resolve links!");
    }
}
```

**Comment by davouid** [comment]
Great.

I'll give 2 a try.
But in the end, i'asking myself if it is not easier to parse the array on my own!
Thank you very much for you time.

**Comment by omarherri** [comment]
This might help anyone facing the same issue. Here's how to handle Contentful's rich text in PHP:

First, install the package:
`composer require contentful/contentful`

Then in your class, add this code:
```
    private Parser $parser;
    private Renderer $renderer;
    
    public function __construct()
    {
        $linkResolver = new \Contentful\Delivery\Client(config('services.contentful.token'), config('services.contentful.space_id'))->getLinkResolver();
        $this->parser = new Parser($linkResolver);
        $this->renderer = new Renderer();
    }
    
    public function parseAndRender(string $richTextData): string
    {
        $node = $this->parser->parse(json_decode($richTextData, true));
        return $this->renderer->render($node);
    }
```

To render any rich text field, use:
 `$this->parseAndRender(json_encode($post->content?->json))`
